server:
  port: 8081
spring:
  application:
#    name: userservice   #user的服务名称
  datasource:
    url: jdbc:mysql://150.158.49.138:3306/cloud_user?useSSL=false
    username: cloud_user
    password: PwPC2TiwBxN3E2PT
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
#        server-addr: 150.158.49.138:8848 #nacos服务地址
        cluster-name: SH #集群名称
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086//eureka