server:
  port: 8080
spring:
  application:
    name: orderservice #order的地址信息
  datasource:
    url: jdbc:mysql://150.158.49.138:3306/cloud_order?useSSL=false
    username: cloud_order
    password: rhbPpa2PpYZdWE5W
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        cluster-name: SH #集群名称
        server-addr: 150.158.49.138:8848 #nacos服务地址
        ephemeral: false #是否是临时实例
#        namespace: c07b1525-efe5-458b-a7ed-f690f7798142 #命名空间
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

path:
  userUrl: "http://userservice/user/"

#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086//eureka


userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  #负载均衡规则

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: #指定饥饿加载的服务名称
      - userservice